/* Public-API behavioral tests. Test observations never depend on script age. */
static void start_neutral(void)
{
    CHECK(action(self) == 0); CHECK(frame()); CHECK(action(self) == 9);
    neutral(); CHECK(calls.x_ops == 0 && calls.l_ops == 0);
}
static void press_jump(void)
{
    start_neutral(); CHECK(frame()); CHECK(action(self) == 9);
    CHECK(self->cpu.buttons == HSD_PAD_X);
    CHECK(self->cpu.lstick.x == 0 && self->cpu.lstick.y == 0);
    CHECK(self->cpu.ltrigger == 0 && self->cpu.rtrigger == 0);
    CHECK(calls.x_ops == 1 && calls.l_ops == 0);
}
static void knees(void)
{
    press_jump();
    observe(self, ftCo_MS_KneeBend, GA_Ground, 1);
    self->mv.co.kneebend.jump_input = JumpInput_XY;
    self->input.held_buttons[0] = self->input.pressed_buttons = HSD_PAD_X;
    CHECK(frame()); neutral(); CHECK(action(self) == 9);
    CHECK(calls.x_ops == 1 && calls.l_ops == 0);
    /* Explicit next native input observation: release sampled during squat. */
    self->input.held_buttons[0] = self->input.pressed_buttons = 0;
    self->mv.co.kneebend.is_short_hop = true;
}
static void dodge(int jump, int direction)
{
    knees();
    observe(self, jump, GA_Air, 0);
    self->mv.co.jump.x4 = false; self->mv.co.jump.x0 = true;
    self->x1968_jumpsUsed = 1; /* FIRST native Jump observation, before Phys. */
    self->cur_pos.y = self->coll_data.cur_pos.y = 1;
    self->self_vel.y = 2; /* Externally observed, NOT generated by X. */
    CHECK(frame()); CHECK(action(self) == 9);
    CHECK(self->cpu.buttons == HSD_PAD_L);
    CHECK(self->cpu.lstick.x == direction * 90 && self->cpu.lstick.y == -64);
    CHECK(abs(self->cpu.lstick.x) <= 127 && self->cpu.lstick.y >= -127);
    CHECK(self->cpu.ltrigger == 0 && self->cpu.rtrigger == 0);
    CHECK(self->cpu.cstick.x == 0 && self->cpu.cstick.y == 0);
    CHECK(calls.x_ops == 1 && calls.l_ops == 1);
}
static void abort_now(void)
{
    CHECK(!frame()); CHECK(action(self) == 0); neutral();
}
static void jumpf_escapeair_ack(void)
{
    setup(); dodge(ftCo_MS_JumpF, 1);
    observe(self, ftCo_MS_EscapeAir, GA_Air, 0);
    CHECK(frame()); neutral(); CHECK(calls.x_ops == 1 && calls.l_ops == 1);
    observe(self, ftCo_MS_LandingFallSpecial, GA_Ground, 0); abort_now();
}
static void jumpb_escapeair_ack(void)
{
    setup(); self->facing_dir = -1; target->cur_pos.x = -80;
    target->coll_data.cur_pos.x = -80;
    dodge(ftCo_MS_JumpB, -1);
    observe(self, ftCo_MS_EscapeAir, GA_Air, 0); CHECK(frame()); neutral();
    observe(self, ftCo_MS_LandingFallSpecial, GA_Ground, 0); abort_now();
}
static void direct_landing_special_ack(void)
{
    setup(); dodge(ftCo_MS_JumpF, 1);
    observe(self, ftCo_MS_LandingFallSpecial, GA_Ground, 0);
    self->cur_pos.y = self->coll_data.cur_pos.y = 0;
    abort_now(); CHECK(calls.l_ops == 1);
}
static void release_observed_kneebend(void)
{
    setup(); knees();
    const float samples[] = { 1, 2, 3 };
    for (unsigned i = 0; i < sizeof(samples) / sizeof(samples[0]); ++i) {
        observe(self, ftCo_MS_KneeBend, GA_Ground, samples[i]);
        CHECK(frame()); neutral(); CHECK(calls.x_ops == 1 && calls.l_ops == 0);
    }
    observe(self, ftCo_MS_JumpF, GA_Air, 0); self->mv.co.jump.x4 = false;
    self->mv.co.jump.x0 = true; self->x1968_jumpsUsed = 1;
    self->cur_pos.y = self->coll_data.cur_pos.y = 1;
    CHECK(frame()); CHECK(self->cpu.buttons == HSD_PAD_L); CHECK(calls.l_ops == 1);
}
static void x_release_tail_without_update(void)
{
    setup(); press_jump(); vm(self); neutral();
    CHECK(!self->cpu.csP && !self->cpu.command_duration);
    for (int i = 0; i < 8; ++i) { vm(self); neutral(); }
    CHECK(self->motion_id == ftCo_MS_Wait && self->ground_or_air == GA_Ground);
    CHECK(calls.x_ops == 1 && calls.l_ops == 0);
}
static void l_release_tail_without_update(void)
{
    setup(); dodge(ftCo_MS_JumpF, 1); vm(self); neutral();
    CHECK(!self->cpu.csP && !self->cpu.command_duration);
    for (int i = 0; i < 8; ++i) { vm(self); neutral(); }
    CHECK(self->motion_id == ftCo_MS_JumpF && self->cur_anim_frame == 0);
    CHECK(calls.x_ops == 1 && calls.l_ops == 1);
}
static void jump_not_inferred_from_input_age(void)
{
    setup(); press_jump();
    for (int i = 0; i < 20; ++i) {
        frame(); neutral(); CHECK(calls.x_ops == 1 && calls.l_ops == 0);
        CHECK(self->motion_id == ftCo_MS_Wait);
    }
    CHECK(action(self) == 0);
}
static void no_kneebend_observation_no_dodge(void)
{
    setup(); press_jump();
    observe(self, ftCo_MS_JumpF, GA_Air, 0);
    self->cur_pos.y = self->coll_data.cur_pos.y = 1;
    abort_now(); CHECK(calls.l_ops == 0);
}
static void no_jump_observation_no_dodge(void)
{
    setup(); knees();
    for (int i = 0; i < 40; ++i) {
        frame(); neutral(); CHECK(calls.x_ops == 1 && calls.l_ops == 0);
    }
    CHECK(action(self) == 0 && self->motion_id == ftCo_MS_KneeBend);
}
static void repeated_jump_sample_no_repeated_l(void)
{
    setup(); dodge(ftCo_MS_JumpF, 1);
    for (int i = 0; i < 20; ++i) {
        frame(); neutral(); CHECK(calls.l_ops == 1 && calls.x_ops == 1);
    }
    CHECK(action(self) == 0);
}
static void missed_neutral_sample(void)
{
    setup(); CHECK(update(self, target)); /* Interpreter did NOT sample. */
    CHECK(!update(self, target)); CHECK(action(self) == 0);
    vm(self); neutral(); CHECK(calls.x_ops == 0 && calls.l_ops == 0);
}
static void missed_x_sample(void)
{
    setup(); start_neutral(); CHECK(update(self, target)); /* no VM */
    observe(self, ftCo_MS_KneeBend, GA_Ground, 1);
    self->mv.co.kneebend.jump_input = JumpInput_XY;
    self->input.held_buttons[0] = self->input.pressed_buttons = HSD_PAD_X;
    abort_now(); CHECK(calls.x_ops == 0 && calls.l_ops == 0);
}
static void missed_kneebend_release_sample(void)
{
    setup(); press_jump(); observe(self, ftCo_MS_KneeBend, GA_Ground, 1);
    self->mv.co.kneebend.jump_input = JumpInput_XY;
    self->input.held_buttons[0] = self->input.pressed_buttons = HSD_PAD_X;
    CHECK(update(self, target)); /* release script never sampled */
    self->input.held_buttons[0] = self->input.pressed_buttons = 0;
    observe(self, ftCo_MS_JumpF, GA_Air, 0);
    self->mv.co.jump.x4 = false; self->mv.co.jump.x0 = true;
    self->x1968_jumpsUsed = 1;
    self->cur_pos.y = self->coll_data.cur_pos.y = 1;
    abort_now(); CHECK(calls.l_ops == 0);
}
static void stale_airborne_start(void)
{
    const int motions[] = { ftCo_MS_JumpF, ftCo_MS_JumpB, ftCo_MS_JumpAerialF,
        ftCo_MS_JumpAerialB, ftCo_MS_Fall, ftCo_MS_EscapeAir, ftCo_MS_AttackAirN };
    for (variant = 0; variant < (int) (sizeof(motions) / sizeof(motions[0])); ++variant) {
        setup(); observe(self, motions[variant], GA_Air, 0);
        expect_no_start(); CHECK(calls.l_ops == 0 && calls.x_ops == 0);
    }
}
static void late_first_jump_sample(void)
{
    const float late[] = { 3, 8, 30, -1, NAN, INFINITY };
    for (variant = 0; variant < (int) (sizeof(late) / sizeof(late[0])); ++variant) {
        setup(); knees(); observe(self, ftCo_MS_JumpF, GA_Air, late[variant]);
        self->mv.co.jump.x4 = false; self->mv.co.jump.x0 = true;
        self->x1968_jumpsUsed = 1;
        self->cur_pos.y = self->coll_data.cur_pos.y = 1;
        abort_now(); CHECK(calls.l_ops == 0);
    }
}
static void nonjump_airborne_after_knees(void)
{
    const int motions[] = { ftCo_MS_JumpAerialF, ftCo_MS_Fall, ftCo_MS_FallSpecial,
        ftCo_MS_AttackAirF, ftCo_MS_EscapeAir, ftCo_MS_LandingFallSpecial };
    for (variant = 0; variant < (int) (sizeof(motions) / sizeof(motions[0])); ++variant) {
        setup(); knees(); observe(self, motions[variant], GA_Air, 0);
        abort_now(); CHECK(calls.l_ops == 0);
    }
}
static void finite_failed_jump_cooldown_retry(void)
{
    setup(); press_jump();
    bool stopped = false;
    for (int i = 0; i < 20; ++i) {
        if (!frame()) { stopped = true; }
        neutral(); CHECK(calls.x_ops == 1 && calls.l_ops == 0);
    }
    CHECK(stopped && action(self) == 0);
    bool retried = false;
    for (int i = 0; i < 240; ++i) {
        if (frame()) { retried = true; neutral(); break; }
    }
    CHECK(retried && action(self) == 9);
    CHECK(frame()); CHECK(self->cpu.buttons == HSD_PAD_X); CHECK(calls.x_ops == 2);
}
static void native_landing_lag_not_rewritten(void)
{
    setup(); dodge(ftCo_MS_JumpF, 1);
    observe(self, ftCo_MS_LandingFallSpecial, GA_Ground, 0);
    self->mv.co.landing.allow_interrupt = false;
    /* Native LandingFallSpecial_Enter computes this animation speed. We supply
     * its observed result, not call/emulate a transition or advance physics. */
    self->frame_speed_mul = (0.1f + self->x2EC) / rules.x344;
    self->x8A4_animBlendFrames = 2.25f;
    self->cur_pos.y = self->coll_data.cur_pos.y = 0;
    self->self_vel = (Vec3) { 2.7f, 0, 0 }; self->gr_vel = 2.7f;
    abort_now();
    const float observations[] = { 1, 4, 12, 24, 29 };
    for (unsigned i = 0; i < sizeof(observations) / sizeof(observations[0]); ++i) {
        observe(self, ftCo_MS_LandingFallSpecial, GA_Ground, observations[i]);
        expect_no_start();
        CHECK(!self->mv.co.landing.allow_interrupt);
        CLOSE(self->frame_speed_mul, (0.1f + self->x2EC) / rules.x344);
        CLOSE(self->self_vel.x, 2.7f); CLOSE(self->gr_vel, 2.7f);
    }
}
static void invalid_public_arguments(void)
{
    setup(); CHECK(!update(NULL, target)); CHECK(action(NULL) == 0);
    suspend(NULL); reset(-1); reset(6); reset(1000);
    CHECK(!update(self, NULL)); CHECK(!update(self, self));
    self->player_id = 6; CHECK(!update(self, target));
    CHECK(action(self) == 0); suspend(self);
    self->player_id = 255; CHECK(!update(self, target));
    CHECK(action(self) == 0); suspend(self);
}
